packages:
  - .
autoInstallPeers: false
minimumReleaseAge: 0
overrides:
  next: '$next'
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  sharp: true
  unrs-resolver: true
  workerd: true
